# Generated by Django 4.2.7 on 2023-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('retailer', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'created_time'), name='unique_name_created_time'),
        ),
    ]
